services:
  db:
    cap_add:
      - SYS_NICE
    restart: always
    build: ./mysql
    ports:
      - 3306:3306
    healthcheck :
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      # waiting the database to start
      timeout: 10s
      retries: 5
  fastapi:
    image: image-fastapi
    build: .
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    container_name: ecgapi-application
    ports:
      - 8000:8000
    volumes:
      - ./:/app
volumes:
  db:
    driver: local